name: Node.js CI Build

on:
  push:
    branches: [ "**" ] # Запускать при пуше/комитe в любую ветку
  pull_request:
    branches: [ "**" ] # Запускать также при пул-реквестах

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Чтение репозитория (Checkout)
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Рекомендуемая LTS версия Node.js
          cache: 'npm'       # Кэширование зависимостей для ускорения сборки

      - name: Установка зависимостей
        run: npm ci

      - name: Сборка проекта
        run: npm run build
